/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BeneficiosRouteImport } from './routes/beneficios'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BusinessBusinessIdRouteImport } from './routes/business.$businessId'
import { Route as BusinessBusinessIdActivatePromoIdRouteImport } from './routes/business.$businessId.activate.$promoId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BeneficiosRoute = BeneficiosRouteImport.update({
  id: '/beneficios',
  path: '/beneficios',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessBusinessIdRoute = BusinessBusinessIdRouteImport.update({
  id: '/business/$businessId',
  path: '/business/$businessId',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessBusinessIdActivatePromoIdRoute =
  BusinessBusinessIdActivatePromoIdRouteImport.update({
    id: '/activate/$promoId',
    path: '/activate/$promoId',
    getParentRoute: () => BusinessBusinessIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/beneficios': typeof BeneficiosRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/business/$businessId': typeof BusinessBusinessIdRouteWithChildren
  '/business/$businessId/activate/$promoId': typeof BusinessBusinessIdActivatePromoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/beneficios': typeof BeneficiosRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/business/$businessId': typeof BusinessBusinessIdRouteWithChildren
  '/business/$businessId/activate/$promoId': typeof BusinessBusinessIdActivatePromoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/beneficios': typeof BeneficiosRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/business/$businessId': typeof BusinessBusinessIdRouteWithChildren
  '/business/$businessId/activate/$promoId': typeof BusinessBusinessIdActivatePromoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajustes'
    | '/beneficios'
    | '/login'
    | '/perfil'
    | '/sitemap.xml'
    | '/business/$businessId'
    | '/business/$businessId/activate/$promoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajustes'
    | '/beneficios'
    | '/login'
    | '/perfil'
    | '/sitemap.xml'
    | '/business/$businessId'
    | '/business/$businessId/activate/$promoId'
  id:
    | '__root__'
    | '/'
    | '/ajustes'
    | '/beneficios'
    | '/login'
    | '/perfil'
    | '/sitemap.xml'
    | '/business/$businessId'
    | '/business/$businessId/activate/$promoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjustesRoute: typeof AjustesRoute
  BeneficiosRoute: typeof BeneficiosRoute
  LoginRoute: typeof LoginRoute
  PerfilRoute: typeof PerfilRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BusinessBusinessIdRoute: typeof BusinessBusinessIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beneficios': {
      id: '/beneficios'
      path: '/beneficios'
      fullPath: '/beneficios'
      preLoaderRoute: typeof BeneficiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/$businessId': {
      id: '/business/$businessId'
      path: '/business/$businessId'
      fullPath: '/business/$businessId'
      preLoaderRoute: typeof BusinessBusinessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/$businessId/activate/$promoId': {
      id: '/business/$businessId/activate/$promoId'
      path: '/activate/$promoId'
      fullPath: '/business/$businessId/activate/$promoId'
      preLoaderRoute: typeof BusinessBusinessIdActivatePromoIdRouteImport
      parentRoute: typeof BusinessBusinessIdRoute
    }
  }
}

interface BusinessBusinessIdRouteChildren {
  BusinessBusinessIdActivatePromoIdRoute: typeof BusinessBusinessIdActivatePromoIdRoute
}

const BusinessBusinessIdRouteChildren: BusinessBusinessIdRouteChildren = {
  BusinessBusinessIdActivatePromoIdRoute:
    BusinessBusinessIdActivatePromoIdRoute,
}

const BusinessBusinessIdRouteWithChildren =
  BusinessBusinessIdRoute._addFileChildren(BusinessBusinessIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjustesRoute: AjustesRoute,
  BeneficiosRoute: BeneficiosRoute,
  LoginRoute: LoginRoute,
  PerfilRoute: PerfilRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BusinessBusinessIdRoute: BusinessBusinessIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
